[[services]]
name = "color.com"
timeout = 0
dependencies = ["fs.color.com"]

#[[services]]
#name = "dumb.color.com"
#dependencies = ["fs.color.com"]

[[services]]
name = "fs.color.com"
timeout = 30
dependencies = []
