syntax = "proto3";

package nullnet_grpc;

service NullnetGrpc {
  // TAP-based clients APIs --------------------------------------------------------------------------------------------

  // Control channel
  rpc ControlChannel(stream MsgId) returns (stream VlanSetup);

  // Services list
  rpc ServicesList(Services) returns (Empty);

  // Proxy-based clients APIs ------------------------------------------------------------------------------------------

  // Proxy
  rpc Proxy(ProxyRequest) returns (Upstream);
}

// TAP-based clients ---------------------------------------------------------------------------------------------------

message VlanSetup {
  MsgId msg_id = 1;
  string client_ethernet = 2;
  string client_veth = 3;
  string server_ethernet = 4;
  string server_veth = 5;
  uint32 vlan_id = 6;
  optional HostMapping host_mapping = 7;
}

message MsgId {
  string id = 1;
}

message Services {
  repeated Service services = 1;
}

message Service {
  string name = 1;
  uint32 port = 2;
}

message HostMapping {
  string ip = 1;
  string name = 2;
}

// Proxy-based clients -------------------------------------------------------------------------------------------------

message ProxyRequest {
  string client_ip = 1;
  string service_name = 2;
}

message Upstream {
  string ip = 1;
  uint32 port = 2;
}

// Misc ----------------------------------------------------------------------------------------------------------------

message Empty { }